mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key-location=privateKey.pem
smallrye.jwt.algo=RS256
quarkus.http.auth.proactive=true

quarkus.mailer.from=noreply@myapp.local
quarkus.mailer.host=sandbox.smtp.mailtrap.io
quarkus.mailer.port=587
quarkus.mailer.username=05d294b773cff2
quarkus.mailer.password=affb517cefd7a7
quarkus.mailer.tls=false
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.mock=false

google.client.id=456614025207-m4ljumnedhiku3qo8t2fgci9r02ukoci.apps.googleusercontent.com

quarkus.default-locale=en
quarkus.locales=en,pl

quarkus.rest.exception-mapping.disable-mapper-for=io.quarkus.resteasy.reactive.jackson.runtime.mappers.BuiltinMismatchedInputExceptionMapper

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:3000
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization
quarkus.http.cors.access-control-allow-credentials=true



