mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key-location=privateKey.pem
smallrye.jwt.algo=RS256
quarkus.http.auth.proactive=true

resend.api.key=re_L9aGypEd_NiXYXSgzH1JaX1rsEfu4LssC
resend.from=onboarding@resend.dev
resend.base.url=https://api.resend.com

google.client.id=456614025207-m4ljumnedhiku3qo8t2fgci9r02ukoci.apps.googleusercontent.com

